project:
  type: website
  resources: 
    - ".well-known/atproto-did"

website:
  title: "Hannah Frick"
  site-url: "https://www.frick.ws"
  description: "Software Engineer | Statistician"
  navbar:
    right:
      - href: about.qmd
        text: About
      - href: speaking.qmd
        text: Speaking
      - href: software.qmd
        text: Software
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - blog.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

execute:
  freeze: auto
