baseURL: https://www.frick.ws
languageCode: en-us
defaultContentLanguage: en
title: Hannah Frick
theme: recluse
rssLimit: 10
copyright: This work is licensed under a Creative Commons Attribution-NonCommercial
  4.0 International License.
enableEmoji: yes
author:
  name: Hannah Frick
blackfriday: {}
taxonomies:
  tag: tags
params:
  code_copy_button: yes
  dateform: Jan 2, 2006
  dateformNum: '2006-01-02'
  dateformNumTime: 2006-01-02 15:04 -0700
  dateformShort: Jan 2
  footerCopyright: ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/"
    target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  homeSubtitle: Software Engineer | Statistician
  justifyContent: no
  relatedPosts: no
  social:
    - name: twitter
      url: https://twitter.com/hfcfrick
    - name: linkedin
      url: https://www.linkedin.com/in/hannah-frick
    - name: github
      url: https://github.com/hfrick
  themeColor: '#494f5c'
menu:
  main:
    - name: Posts
      url: post/
      weight: 10
    - name: Speaking
      url: speaking/
      weight: 20
    - name: Publications
      url: publications/
      weight: 30
    - name: Software
      url: software/
      weight: 40
    - name: Teaching
      url: teaching/
      weight: 50
    - name: About
      url: about/
      weight: 100

markup:
  goldmark:
    renderer:
      unsafe: true

ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
