
### Refereed publications and technical reports

- Frick H, Kosmidis I (2017). _trackeR: Infrastructure for Running and Cycling Data from GPS-Enabled Tracking Devices in R_. Journal of Statistical Software, [82(7)](https://www.jstatsoft.org/article/view/v082i07).

- Frick H, Strobl C, Zeileis A (2015). _Rasch Mixture Models for DIF Detection: A Comparison of Old and New Score Specifications_. Educational and Psychological Measurement, [75(2)](http://epm.sagepub.com/content/75/2/208).

- Frick H, Strobl C, Zeileis A (2014). _To Split or to Mix? Tree vs. Mixture Models for Detecting Subgroups_. COMPSTAT 2014 - Proceedings in Computational Statistics, pp. 379--386. The International Statistical Institute/International Association for Statistical Computing. ISBN 978-2-8399-1347-8. [[.pdf]](papers/Frick+Strobl+Zeileis-2014.pdf)

- Frick U, Frick H, Langguth B, Landgrebe M, H&uuml;bner-Liebermann B, Hajak G (2013). _The Revolving Door Phenomenon Revisited: Time to Readmission in 17'415 Patients with 37'697 Hospitalisations at a German Psychiatric Hospital_. PLOS ONE, [8(10)](https://doi.org/10.1371/journal.pone.0075612).

- Frick H, Strobl C, Leisch F, Zeileis A (2012). _Flexible Rasch Mixture Models with Package psychomix_. Journal of Statistical Software, [48(7)](http://www.jstatsoft.org/v48/i07/).

- Gmel G, Shield K, Frick H, Kehoe T, Gmel G, Rehm J (2011). _Estimating Uncertainty of Alcohol-Attributable Fractions for Infectious and Chronic Diseases_. BMC Medical Research Methodology, [11(1)](https://www.biomedcentral.com/1471-2288/11/48).

- Frick H (2010). _Mixtures of Rasch Models Based on Conditional Maximum Likelihood Estimation: Implementation, Validation and Generalization of Rost's Approach_. Masters Thesis, Department of Statistics, Ludwig-Maximilians-Universit&auml;t M&uuml;nchen.

- Frick U, Frick H (2010). _'Dreht&uuml;re' in der station&auml;ren Psychiatrie der Schweiz? Mythos oder empirische Realit&auml;t?_ Obsan Dossier 12, Schweizerisches Gesundheitsobservatorium Obsan.

- Frick U, Frick H (2010a). _'Heavy Use' in der station&auml;ren Psychiatrie der Schweiz? Ergebnisse aus der Medizinischen Statistik der Krankenh&auml;user_. Obsan Dossier 11, Schweizerisches Gesundheitsobservatorium Obsan.

- Frick U, Frick H (2008). _Basisdaten station&auml;rer psychiatrischer Behandlungen: Vertiefungsstudie `Heavy User' - Literaturanalyse_. Forschungsprotokoll 5. Schweizerisches Gesundheitsobservatorium Obsan.


### PhD thesis

_Mixture Models in Statistics and Psychometrics - Detecting Subgroups and Differential Item Functioning_ (2014, Department of Mathematics,     Universit&auml;t Innsbruck) [[.pdf]](papers/Frick_thesis.pdf)

